In [1]:
print("Supermarket Food Waste Reduction Project")

Supermarket Food Waste Reduction Project

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
import pandas as pd

df = pd.read_csv("Grocery_Inventory_and_Sales_Dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.head()

,Product_ID,Product_Name,Catagory,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status
0,29-205-1132,Sushi Rice,Grains & Pulses,38-037-1699,Jaxnation,22,72,70,$4.50,8/16/2024,6/29/2024,9/19/2024,48 Del Sol Trail,32,19,Discontinued
1,40-681-9981,Arabica Coffee,Beverages,54-470-2479,Feedmix,45,77,2,$20.00,11/1/2024,5/29/2024,5/8/2024,36 3rd Place,85,1,Discontinued
2,06-955-3428,Black Rice,Grains & Pulses,54-031-2945,Vinder,30,38,83,$6.00,8/3/2024,6/10/2024,9/22/2024,3296 Walton Court,31,34,Backordered
3,71-594-6552,Long Grain Rice,Grains & Pulses,63-492-7603,Brightbean,12,59,62,$1.50,12/8/2024,2/19/2025,4/17/2024,3 Westerfield Crossing,95,99,Active
4,57-437-1828,Plum,Fruits & Vegetables,54-226-4308,Topicstorm,37,30,74,$4.00,7/3/2024,10/11/2024,10/5/2024,15068 Scoville Court,62,25,Backordered

In [5]:
df.shape

(990, 16)

In [6]:
df.columns

Index(['Product_ID', 'Product_Name', 'Catagory', 'Supplier_ID',
       'Supplier_Name', 'Stock_Quantity', 'Reorder_Level', 'Reorder_Quantity',
       'Unit_Price', 'Date_Received', 'Last_Order_Date', 'Expiration_Date',
       'Warehouse_Location', 'Sales_Volume', 'Inventory_Turnover_Rate',
       'Status'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product_ID               990 non-null    str
 1   Product_Name             990 non-null    str
 2   Catagory                 989 non-null    str
 3   Supplier_ID              990 non-null    str
 4   Supplier_Name            990 non-null    str
 5   Stock_Quantity           990 non-null    int64
 6   Reorder_Level            990 non-null    int64
 7   Reorder_Quantity         990 non-null    int64
 8   Unit_Price               990 non-null    str
 9   Date_Received            990 non-null    str
 10  Last_Order_Date          990 non-null    str
 11  Expiration_Date          990 non-null    str
 12  Warehouse_Location       990 non-null    str
 13  Sales_Volume             990 non-null    int64
 14  Inventory_Turnover_Rate  990 non-null    int64
 15  Status                   990 non-null    str
dtypes: int64(5), str(11)
memory usage: 231.7 KB

In [8]:
df.describe()

,Stock_Quantity,Reorder_Level,Reorder_Quantity,Sales_Volume,Inventory_Turnover_Rate
count,990.000000,990.000000,990.000000,990.000000,990.000000
mean,55.609091,51.215152,51.913131,58.925253,50.150505
std,26.300775,29.095241,29.521059,23.002318,28.798954
min,10.000000,1.000000,1.000000,20.000000,1.000000
25%,33.000000,25.250000,25.000000,39.000000,25.000000
50%,56.000000,53.000000,54.000000,58.000000,50.000000
75%,79.000000,77.000000,77.000000,78.000000,74.750000
max,100.000000,100.000000,100.000000,100.000000,100.000000

In [9]:
df.isnull().sum()

Product_ID                 0
Product_Name               0
Catagory                   1
Supplier_ID                0
Supplier_Name              0
Stock_Quantity             0
Reorder_Level              0
Reorder_Quantity           0
Unit_Price                 0
Date_Received              0
Last_Order_Date            0
Expiration_Date            0
Warehouse_Location         0
Sales_Volume               0
Inventory_Turnover_Rate    0
Status                     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

Product_ID                   str
Product_Name                 str
Catagory                     str
Supplier_ID                  str
Supplier_Name                str
Stock_Quantity             int64
Reorder_Level              int64
Reorder_Quantity           int64
Unit_Price                   str
Date_Received                str
Last_Order_Date              str
Expiration_Date              str
Warehouse_Location           str
Sales_Volume               int64
Inventory_Turnover_Rate    int64
Status                       str
dtype: object

In [12]:
df[df["Category"].isnull()]

KeyError: 'Category'

In [13]:
df.columns.tolist()

['Product_ID',
 'Product_Name',
 'Catagory',
 'Supplier_ID',
 'Supplier_Name',
 'Stock_Quantity',
 'Reorder_Level',
 'Reorder_Quantity',
 'Unit_Price',
 'Date_Received',
 'Last_Order_Date',
 'Expiration_Date',
 'Warehouse_Location',
 'Sales_Volume',
 'Inventory_Turnover_Rate',
 'Status']

In [14]:
df.rename(columns={"Catagory": "Category"}, inplace=True)

In [15]:
df.columns.tolist()

['Product_ID',
 'Product_Name',
 'Category',
 'Supplier_ID',
 'Supplier_Name',
 'Stock_Quantity',
 'Reorder_Level',
 'Reorder_Quantity',
 'Unit_Price',
 'Date_Received',
 'Last_Order_Date',
 'Expiration_Date',
 'Warehouse_Location',
 'Sales_Volume',
 'Inventory_Turnover_Rate',
 'Status']

In [16]:
df[df["Category"].isnull()]

,Product_ID,Product_Name,Category,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status
685,10-378-9729,Cabbage,NaN,83-941-9620,Rooxo,69,21,68,$66.55,12/23/2024,11/26/2024,9/21/2024,2 Butterfield Pass,36,35,Discontinued

In [17]:
df.loc[df["Product_Name"] == "Cabbage", "Category"] = "Fruits & Vegetables"

In [18]:
df[df["Product_Name"] == "Cabbage"]

,Product_ID,Product_Name,Category,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status
23,67-025-1245,Cabbage,Fruits & Vegetables,28-575-0716,Chatterbridge,88,46,55,$1.00,4/9/2024,3/6/2024,8/12/2024,51890 Lindbergh Terrace,73,63,Active
501,21-013-3508,Cabbage,Fruits & Vegetables,64-489-8494,Meevee,12,95,49,$1.00,6/9/2024,6/13/2024,11/10/2024,84305 Fair Oaks Plaza,25,23,Backordered
521,79-428-8753,Cabbage,Fruits & Vegetables,29-521-7910,Skivee,62,79,95,$1.00,5/16/2024,7/6/2024,12/30/2024,9 Holmberg Circle,34,12,Active
652,45-380-4627,Cabbage,Fruits & Vegetables,20-201-5639,Zoombox,90,1,40,$0.90,10/20/2024,1/11/2025,2/16/2025,0 Thackeray Point,52,19,Discontinued
685,10-378-9729,Cabbage,Fruits & Vegetables,83-941-9620,Rooxo,69,21,68,$66.55,12/23/2024,11/26/2024,9/21/2024,2 Butterfield Pass,36,35,Discontinued
788,75-927-9108,Cabbage,Fruits & Vegetables,27-406-7972,Topdrive,24,32,17,$1.00,9/29/2024,6/17/2024,7/2/2024,43 Washington Street,55,72,Discontinued
806,82-538-4809,Cabbage,Fruits & Vegetables,74-357-2990,Twitternation,83,61,4,$1.00,9/16/2024,11/5/2024,10/24/2024,700 Northland Crossing,35,7,Backordered
987,31-745-6850,Cabbage,Fruits & Vegetables,96-215-2767,Lajo,94,90,12,$0.90,10/3/2024,10/24/2024,11/1/2024,081 Jana Lane,98,71,Active

In [19]:
df.isnull().sum()

Product_ID                 0
Product_Name               0
Category                   0
Supplier_ID                0
Supplier_Name              0
Stock_Quantity             0
Reorder_Level              0
Reorder_Quantity           0
Unit_Price                 0
Date_Received              0
Last_Order_Date            0
Expiration_Date            0
Warehouse_Location         0
Sales_Volume               0
Inventory_Turnover_Rate    0
Status                     0
dtype: int64

In [20]:
df["Date_Received"] = pd.to_datetime(df["Date_Received"])
df["Last_Order_Date"] = pd.to_datetime(df["Last_Order_Date"])
df["Expiration_Date"] = pd.to_datetime(df["Expiration_Date"])

print("Date columns converted successfully!")

Date columns converted successfully!

In [21]:
df[["Date_Received", "Last_Order_Date", "Expiration_Date"]].dtypes

Date_Received      datetime64[us]
Last_Order_Date    datetime64[us]
Expiration_Date    datetime64[us]
dtype: object

In [22]:
df["Unit_Price"].dtype

In [23]:
df["Unit_Price"] = (
    df["Unit_Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .astype(float)
)

print("Unit_Price converted successfully!")

Unit_Price converted successfully!

In [24]:
df["Unit_Price"].head()

0     4.5
1    20.0
2     6.0
3     1.5
4     4.0
Name: Unit_Price, dtype: float64

In [25]:
df["Unit_Price"].dtype

dtype('float64')

In [26]:
df[[
    "Stock_Quantity",
    "Reorder_Level",
    "Reorder_Quantity",
    "Unit_Price",
    "Sales_Volume",
    "Inventory_Turnover_Rate"
]].describe()

,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate
count,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000
mean,55.609091,51.215152,51.913131,5.924192,58.925253,50.150505
std,26.300775,29.095241,29.521059,6.491280,23.002318,28.798954
min,10.000000,1.000000,1.000000,0.200000,20.000000,1.000000
25%,33.000000,25.250000,25.000000,2.500000,39.000000,25.000000
50%,56.000000,53.000000,54.000000,4.225000,58.000000,50.000000
75%,79.000000,77.000000,77.000000,7.000000,78.000000,74.750000
max,100.000000,100.000000,100.000000,98.430000,100.000000,100.000000

In [27]:
numeric_columns = [
    "Stock_Quantity",
    "Reorder_Level",
    "Reorder_Quantity",
    "Unit_Price",
    "Sales_Volume",
    "Inventory_Turnover_Rate"
]

for column in numeric_columns:
    print(column, ":", (df[column] < 0).sum())

Stock_Quantity : 0
Reorder_Level : 0
Reorder_Quantity : 0
Unit_Price : 0
Sales_Volume : 0
Inventory_Turnover_Rate : 0

In [28]:
print("Products with zero price:", (df["Unit_Price"] == 0).sum())

Products with zero price: 0

In [29]:
print("Products with zero stock:", (df["Stock_Quantity"] == 0).sum())

Products with zero stock: 0

In [1]:
df.to_csv("cleaned_supermarket_data.csv", index=False)

print("Cleaned dataset saved successfully!")

NameError: name 'df' is not defined

In [2]:
df.to_csv("cleaned_supermarket_data.csv", index=False)

NameError: name 'df' is not defined

In [3]:
import pandas as pd

# Load the original dataset
df = pd.read_csv("Grocery_Inventory_and_Sales_Dataset.csv")

# Fix the category column name if required
if "Catagory" in df.columns:
    df.rename(columns={"Catagory": "Category"}, inplace=True)

# Fill the missing category for Cabbage
df.loc[df["Product_Name"] == "Cabbage", "Category"] = "Fruits & Vegetables"

# Convert date columns
df["Date_Received"] = pd.to_datetime(df["Date_Received"])
df["Last_Order_Date"] = pd.to_datetime(df["Last_Order_Date"])
df["Expiration_Date"] = pd.to_datetime(df["Expiration_Date"])

# Convert Unit_Price from text to numeric
df["Unit_Price"] = (
    df["Unit_Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .astype(float)
)

print("Dataset loaded and cleaned successfully!")

Dataset loaded and cleaned successfully!

In [4]:
df.to_csv("cleaned_supermarket_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [5]:
print("Earliest Date Received:", df["Date_Received"].min())
print("Latest Date Received:", df["Date_Received"].max())

print("Earliest Expiration Date:", df["Expiration_Date"].min())
print("Latest Expiration Date:", df["Expiration_Date"].max())

Earliest Date Received: 2024-02-25 00:00:00
Latest Date Received: 2025-02-24 00:00:00
Earliest Expiration Date: 2024-02-25 00:00:00
Latest Expiration Date: 2025-02-24 00:00:00

In [6]:
df["Shelf_Life_Days"] = (
    df["Expiration_Date"] - df["Date_Received"]
).dt.days

print("Shelf life calculated successfully!")

Shelf life calculated successfully!

In [7]:
df["Shelf_Life_Days"].describe()

count    990.000000
mean       0.185859
std      150.125993
min     -365.000000
25%     -106.750000
50%       -1.500000
75%      100.750000
max      344.000000
Name: Shelf_Life_Days, dtype: float64

In [8]:
df[df["Shelf_Life_Days"] < 0][[
    "Product_Name",
    "Date_Received",
    "Expiration_Date",
    "Shelf_Life_Days",
    "Stock_Quantity",
    "Sales_Volume"
]].head(20)

,Product_Name,Date_Received,Expiration_Date,Shelf_Life_Days,Stock_Quantity,Sales_Volume
1,Arabica Coffee,2024-11-01,2024-05-08,-177,45,85
3,Long Grain Rice,2024-12-08,2024-04-17,-235,12,95
5,All-Purpose Flour,2024-12-03,2024-09-05,-89,55,34
9,Egg (Duck),2024-11-18,2024-07-08,-133,43,27
11,White Sugar,2024-10-19,2024-10-14,-5,91,100
12,Rye Bread,2024-12-13,2024-07-18,-148,26,47
16,Bread Flour,2024-11-16,2024-04-05,-225,27,66
17,Swiss Cheese,2024-09-10,2024-07-01,-71,49,78
18,Arabica Coffee,2024-05-29,2024-05-05,-24,55,46
20,Spinach,2024-10-07,2024-06-22,-107,72,82
22,Green Beans,2024-09-30,2024-04-25,-158,81,20
24,Parmesan Cheese,2024-12-21,2024-09-30,-82,63,59
26,Egg (Quail),2024-11-05,2024-06-26,-132,97,97
27,Mushrooms,2024-06-24,2024-03-17,-99,72,94
30,Cucumber,2024-05-03,2024-03-06,-58,19,31
32,Olive Oil,2024-08-13,2024-03-05,-161,47,42
33,Herbal Tea,2024-11-05,2024-06-23,-135,77,25
38,Zucchini,2024-12-22,2024-09-19,-94,61,79
39,Short Grain Rice,2025-01-21,2024-08-24,-150,60,47
41,Lemon,2024-06-24,2024-06-05,-19,12,66

In [9]:
print(
    "Products with negative shelf life:",
    (df["Shelf_Life_Days"] < 0).sum()
)

Products with negative shelf life: 496

In [10]:
df["Status"].value_counts()

Status
Discontinued    333
Active          332
Backordered     325
Name: count, dtype: int64

In [11]:
df["Status"].unique()

<ArrowStringArray>
['Discontinued', 'Backordered', 'Active']
Length: 3, dtype: str

In [12]:
df[[
    "Stock_Quantity",
    "Sales_Volume",
    "Inventory_Turnover_Rate"
]].describe()

       Stock_Quantity  Sales_Volume  Inventory_Turnover_Rate
count      990.000000    990.000000               990.000000
mean        55.609091     58.925253                50.150505
std         26.300775     23.002318                28.798954
min         10.000000     20.000000                 1.000000
25%         33.000000     39.000000                25.000000
50%         56.000000     58.000000                50.000000
75%         79.000000     78.000000                74.750000
max        100.000000    100.000000               100.000000

In [13]:
(df["Sales_Volume"] > df["Stock_Quantity"]).sum()

np.int64(529)

In [14]:
df[df["Sales_Volume"] > df["Stock_Quantity"]][[
    "Product_Name",
    "Stock_Quantity",
    "Sales_Volume",
    "Status"
]].head(10)

       Product_Name  Stock_Quantity  Sales_Volume        Status
0        Sushi Rice              22            32  Discontinued
1    Arabica Coffee              45            85  Discontinued
2        Black Rice              30            31   Backordered
3   Long Grain Rice              12            95        Active
4              Plum              37            62   Backordered
10  Long Grain Rice              62           100  Discontinued
11      White Sugar              91           100   Backordered
12        Rye Bread              26            47  Discontinued
14     Strawberries              54            63        Active
16      Bread Flour              27            66        Active

In [15]:
df["Inventory_Pressure_Ratio"] = (
    df["Sales_Volume"] / df["Stock_Quantity"]
)

print("Inventory Pressure Ratio created successfully!")

Inventory Pressure Ratio created successfully!

In [16]:

df["Inventory_Pressure_Ratio"].describe()

count    990.000000
mean       1.483237
std        1.297907
min        0.200000
25%        0.692308
50%        1.056711
75%        1.812846
max       10.000000
Name: Inventory_Pressure_Ratio, dtype: float64

In [17]:
df["Overstock_Ratio"] = (
    df["Stock_Quantity"] / df["Sales_Volume"]
)

print("Overstock Ratio created successfully!")

Overstock Ratio created successfully!

In [18]:
df["Overstock_Ratio"].describe()

count    990.000000
mean       1.132402
std        0.795316
min        0.100000
25%        0.551619
50%        0.946333
75%        1.444444
max        5.000000
Name: Overstock_Ratio, dtype: float64

In [19]:
df[[
    "Product_Name",
    "Stock_Quantity",
    "Sales_Volume",
    "Overstock_Ratio"
]].head(10)

        Product_Name  Stock_Quantity  Sales_Volume  Overstock_Ratio
0         Sushi Rice              22            32         0.687500
1     Arabica Coffee              45            85         0.529412
2         Black Rice              30            31         0.967742
3    Long Grain Rice              12            95         0.126316
4               Plum              37            62         0.596774
5  All-Purpose Flour              55            34         1.617647
6           Corn Oil              96            67         1.432836
7        Egg (Goose)              44            21         2.095238
8       Greek Yogurt              91            56         1.625000
9         Egg (Duck)              43            27         1.592593

In [20]:
df["Overstock_Ratio"] = (
    df["Stock_Quantity"] / df["Sales_Volume"]
)

print("Overstock Ratio created successfully!")

Overstock Ratio created successfully!

In [21]:
df["Overstock_Ratio"].describe()

count    990.000000
mean       1.132402
std        0.795316
min        0.100000
25%        0.551619
50%        0.946333
75%        1.444444
max        5.000000
Name: Overstock_Ratio, dtype: float64

In [22]:
def classify_overstock(ratio):
    if ratio < 0.75:
        return "Low Risk"
    elif ratio <= 1.50:
        return "Medium Risk"
    else:
        return "High Risk"


df["Overstock_Risk"] = df["Overstock_Ratio"].apply(classify_overstock)

print("Overstock risk categories created successfully!")

Overstock risk categories created successfully!

In [23]:
df["Overstock_Risk"].value_counts()

Overstock_Risk
Medium Risk    391
Low Risk       367
High Risk      232
Name: count, dtype: int64

In [24]:
df["Overstock_Risk"].value_counts(normalize=True) * 100

Overstock_Risk
Medium Risk    39.494949
Low Risk       37.070707
High Risk      23.434343
Name: proportion, dtype: float64

In [25]:
    category_overstock = (
    df.groupby("Category")["Overstock_Ratio"]
    .mean()
    .sort_values(ascending=False)
)

category_overstock

IndentationError: unexpected indent (1235013392.py, line 1)

In [26]:
category_overstock = (
    df.groupby("Category")["Overstock_Ratio"]
    .mean()
    .sort_values(ascending=False)
)

category_overstock

Category
Seafood                1.205637
Dairy                  1.169440
Fruits & Vegetables    1.163319
Grains & Pulses        1.119278
Bakery                 1.054196
Oils & Fats            1.039172
Beverages              1.019995
Name: Overstock_Ratio, dtype: float64

In [27]:
powerbi_df = df.drop(columns=["Shelf_Life_Days"])

powerbi_df.to_csv(
    "PowerBI_Supermarket_Food_Waste.csv",
    index=False
)

print("Power BI dataset created successfully!")

Power BI dataset created successfully!